In [109]:
import urllib.request, json, timeit, pandas as pd, numpy as np

In [110]:
start = timeit.default_timer()
df_shopee_item_append = pd.DataFrame

shopee_url = "https://shopee.co.id/api/v4/search/search_items?by=relevancy&limit=60&match_id=1028154&newest=0&order=desc&page_type=collection&scenario=PAGE_COLLECTION_SEARCH&version=2"
print(shopee_url)
with urllib.request.urlopen(shopee_url) as url:
  data_shopee = json.loads(url.read().decode())

  
  df_shopee = pd.DataFrame.from_dict(data_shopee, orient='index')
  df_shopee = pd.DataFrame(df_shopee.transpose())
  df_shopee_item = pd.DataFrame(df_shopee['items'])
  df_shopee_item = pd.DataFrame(df_shopee_item['items'].values.tolist())
  df_shopee_item = df_shopee_item.transpose()
  df_shopee_item = pd.DataFrame(df_shopee_item[0].values.tolist())
  df_shopee_name = pd.DataFrame(df_shopee_item['item_basic'])
  df_shopee_name = pd.DataFrame(df_shopee_name['item_basic'].values.tolist())

  

  print('===============')

stop = timeit.default_timer()
print('Time: ', stop - start)

https://shopee.co.id/api/v4/search/search_items?by=relevancy&limit=60&match_id=1028154&newest=0&order=desc&page_type=collection&scenario=PAGE_COLLECTION_SEARCH&version=2
===============
Time:  3.7677212479993614

In [111]:
df_shopee

  bff_meta  ... search_sessionid
0     None  ...             None

[1 rows x 23 columns]

In [112]:
df_shopee_item

                                           item_basic  ... biz_json
0   {'itemid': 121456177, 'shopid': 1521932, 'name...  ...     None
1   {'itemid': 884658629, 'shopid': 392752, 'name'...  ...     None
2   {'itemid': 6234078253, 'shopid': 194992662, 'n...  ...     None
3   {'itemid': 1545698853, 'shopid': 20458255, 'na...  ...     None
4   {'itemid': 3294568795, 'shopid': 65323877, 'na...  ...     None
5   {'itemid': 6035103111, 'shopid': 194992662, 'n...  ...     None
6   {'itemid': 51978211, 'shopid': 1521932, 'name'...  ...     None
7   {'itemid': 6418162127, 'shopid': 858776, 'name...  ...     None
8   {'itemid': 1115347781, 'shopid': 65323877, 'na...  ...     None
9   {'itemid': 5125977880, 'shopid': 194992662, 'n...  ...     None
10  {'itemid': 1136521804, 'shopid': 1521932, 'nam...  ...     None
11  {'itemid': 4957666654, 'shopid': 264500744, 'n...  ...     None
12  {'itemid': 1115347778, 'shopid': 65323877, 'na...  ...     None
13  {'itemid': 1179857151, 'shopid': 65323877, 'na...  ...     None
14  {'itemid': 2334368192, 'shopid': 65323877, 'na...  ...     None
15  {'itemid': 5445621089, 'shopid': 52733860, 'na...  ...     None
16  {'itemid': 7542409612, 'shopid': 52733860, 'na...  ...     None
17  {'itemid': 1408491941, 'shopid': 65323877, 'na...  ...     None
18  {'itemid': 2004565903, 'shopid': 65323877, 'na...  ...     None
19  {'itemid': 6835103028, 'shopid': 194992662, 'n...  ...     None
20  {'itemid': 8462510362, 'shopid': 318835972, 'n...  ...     None
21  {'itemid': 2759274067, 'shopid': 65323877, 'na...  ...     None
22  {'itemid': 1408491807, 'shopid': 65323877, 'na...  ...     None
23  {'itemid': 5847844259, 'shopid': 194992662, 'n...  ...     None
24  {'itemid': 6551609877, 'shopid': 20458255, 'na...  ...     None
25  {'itemid': 7142205909, 'shopid': 52733860, 'na...  ...     None
26  {'itemid': 7619188286, 'shopid': 20090785, 'na...  ...     None
27  {'itemid': 6361450321, 'shopid': 65323877, 'na...  ...     None
28  {'itemid': 1414769272, 'shopid': 65323877, 'na...  ...     None
29  {'itemid': 10918845891, 'shopid': 65323877, 'n...  ...     None
30  {'itemid': 9279915117, 'shopid': 65323877, 'na...  ...     None
31  {'itemid': 5039205414, 'shopid': 65323877, 'na...  ...     None
32  {'itemid': 5945996828, 'shopid': 20458255, 'na...  ...     None
33  {'itemid': 4723309448, 'shopid': 20090785, 'na...  ...     None
34  {'itemid': 1948978371, 'shopid': 65323877, 'na...  ...     None
35  {'itemid': 8878010547, 'shopid': 65323877, 'na...  ...     None
36  {'itemid': 2091926226, 'shopid': 65323877, 'na...  ...     None
37  {'itemid': 3495031835, 'shopid': 65323877, 'na...  ...     None
38  {'itemid': 4826952150, 'shopid': 65323877, 'na...  ...     None
39  {'itemid': 9611565813, 'shopid': 70448302, 'na...  ...     None
40  {'itemid': 3845717039, 'shopid': 52733860, 'na...  ...     None
41  {'itemid': 8779906691, 'shopid': 65323877, 'na...  ...     None
42  {'itemid': 1408491951, 'shopid': 65323877, 'na...  ...     None
43  {'itemid': 3950079537, 'shopid': 65323877, 'na...  ...     None
44  {'itemid': 8485861287, 'shopid': 318835972, 'n...  ...     None
45  {'itemid': 10019473592, 'shopid': 65323877, 'n...  ...     None
46  {'itemid': 5294739890, 'shopid': 65323877, 'na...  ...     None
47  {'itemid': 3817493191, 'shopid': 112401807, 'n...  ...     None
48  {'itemid': 12947565918, 'shopid': 52733860, 'n...  ...     None
49  {'itemid': 9120150608, 'shopid': 318835972, 'n...  ...     None
50  {'itemid': 7894815220, 'shopid': 65323877, 'na...  ...     None
51  {'itemid': 4291453165, 'shopid': 318835972, 'n...  ...     None
52  {'itemid': 13636084288, 'shopid': 20090785, 'n...  ...     None
53  {'itemid': 9579914758, 'shopid': 65323877, 'na...  ...     None
54  {'itemid': 10746299623, 'shopid': 318835972, '...  ...     None
55  {'itemid': 8979912394, 'shopid': 65323877, 'na...  ...     None
56  {'itemid': 9379241028, 'shopid': 65323877, 'na...  ...     None
57  {'itemid': 3223473213, 'shopid': 20090785, 'na...  ...     None
58  {'itemid': 3258077625, 'shopid': 65323877, 'na...  ...     None
59  {'itemid': 8579241266, 'shopid': 65323877, 'na...  ...     None

[60 rows x 22 columns]

In [113]:
df_shopee_name

         itemid     shopid  ... pack_size deep_discount_skin
0     121456177    1521932  ...      None               None
1     884658629     392752  ...      None               None
2    6234078253  194992662  ...      None               None
3    1545698853   20458255  ...      None               None
4    3294568795   65323877  ...      None               None
5    6035103111  194992662  ...      None               None
6      51978211    1521932  ...      None               None
7    6418162127     858776  ...      None               None
8    1115347781   65323877  ...      None               None
9    5125977880  194992662  ...      None               None
10   1136521804    1521932  ...      None               None
11   4957666654  264500744  ...      None               None
12   1115347778   65323877  ...      None               None
13   1179857151   65323877  ...      None               None
14   2334368192   65323877  ...      None               None
15   5445621089   52733860  ...      None               None
16   7542409612   52733860  ...      None               None
17   1408491941   65323877  ...      None               None
18   2004565903   65323877  ...      None               None
19   6835103028  194992662  ...      None               None
20   8462510362  318835972  ...      None               None
21   2759274067   65323877  ...      None               None
22   1408491807   65323877  ...      None               None
23   5847844259  194992662  ...      None               None
24   6551609877   20458255  ...      None               None
25   7142205909   52733860  ...      None               None
26   7619188286   20090785  ...      None               None
27   6361450321   65323877  ...      None               None
28   1414769272   65323877  ...      None               None
29  10918845891   65323877  ...      None               None
30   9279915117   65323877  ...      None               None
31   5039205414   65323877  ...      None               None
32   5945996828   20458255  ...      None               None
33   4723309448   20090785  ...      None               None
34   1948978371   65323877  ...      None               None
35   8878010547   65323877  ...      None               None
36   2091926226   65323877  ...      None               None
37   3495031835   65323877  ...      None               None
38   4826952150   65323877  ...      None               None
39   9611565813   70448302  ...      None               None
40   3845717039   52733860  ...      None               None
41   8779906691   65323877  ...      None               None
42   1408491951   65323877  ...      None               None
43   3950079537   65323877  ...      None               None
44   8485861287  318835972  ...      None               None
45  10019473592   65323877  ...      None               None
46   5294739890   65323877  ...      None               None
47   3817493191  112401807  ...      None               None
48  12947565918   52733860  ...      None               None
49   9120150608  318835972  ...      None               None
50   7894815220   65323877  ...      None               None
51   4291453165  318835972  ...      None               None
52  13636084288   20090785  ...      None               None
53   9579914758   65323877  ...      None               None
54  10746299623  318835972  ...      None               None
55   8979912394   65323877  ...      None               None
56   9379241028   65323877  ...      None               None
57   3223473213   20090785  ...      None               None
58   3258077625   65323877  ...      None               None
59   8579241266   65323877  ...      None               None

[60 rows x 75 columns]

Warning: Total number of columns (75) exceeds max_columns (20) limiting to first (20) columns.

In [116]:
pv = pd.pivot_table(df_shopee_name, index= "name", values=["price"], aggfunc=np.sum)

In [104]:
pv

                                                          price
name
Beng Beng Chocolate Crisp Wafer - Netto 20 bks ...   2780000000
Cadbury Coklat Lickables Cup 20g Untuk Camilan ...   1390000000
Cadbury Dairy Milk Chocolate Fruit & Nut Regula...    770000000
Cadbury Dairy Milk Hazelnut 62g                      1700000000
Chacha Disney Collection 35 g                         970000000
Chocolate Monggo 80g Collection | 20 Variants |...   4900000000
Chocolatos Dark 20 x 16 gr (1 Box)                   1820000000
Chocolatos Dark Mini Kemasan 2 x 30 gr                350000000
Chocolatos Dark Mini Kemasan 24g x2                   350000000
Choki Choki Chococashew - Netto 20 pcs x 11 gr       1750000000
Coco Fruit and Nut Bar 50 gr                          850000000
Coklat Krikil Original                               2100000000
Delfi Bar bar 18 gr                                   240000000
Delfi Chic Choc Biskuit Cokelat 2 x 50 gr            1710000000
Delfi Cokelat Cashew 50 gr                           1210000000
Delfi Hot Cocoa Indulgence 5 x 25 gr                 1780000000
Delfi Maltitos Cokelat 40 gr                          690000000
Delfi Orion Chocopie Cacao Choco Pie Dark 180 gr     1830000000
Delfi Twister Black Vanilla 80gr                      690000000
Delfi Twister Mini Black Vanilla 2 x 80 gr           1370000000
Frisian Flag Kompleta Coklat 800 gr x 3             20570000000
Gery Meiseis 7 gr Twinpack0                           900000000
Gery Meiseis 7 gr x10                                 430000000
Hagelslag Ceres Festive 90 gr                        1060000000
Hello Panda Biskuit Choco 45 gr                       850000000
Hello Panda Choco 2 x 45 gr                          1620000000
Kinder Bueno Chocolate 43 gr                         1240000000
Kinder Joy (Girls) Camilan Cokelat 2 x 20 gr         2350000000
Kinder Joy Cokelat Compound Krispi 20 gr             1240000000
Kit Kat Chocolate Green Tea 4 Fingers 35 gr          1160000000
Kit Kat Green Tea 4 Fingers 35g                      1140000000
Kit Kat Green Tea 4 Fingers 35g - 6 pcs              6320000000
L'AGIE Animal Series Milk Chocolate - Netto 25 gr     260000000
Loacker Quadratini Wafer Cokelat Dark Chocolate...   3350000000
MILO Coklat Nuggets 25g x 2pcs                       2090000000
Mayasi Crispy Crepes Wafer Roll Cokelat 90 gr         760000000
Meiji Yan Yan Topping Chocolate 30 gr                 550000000
Milkuat Susu UHT Cokelat 50 mL                        110000000
Milo Cokelat Nuggets 2 x 25 gr                       2090000000
Milo Energy Cube SATUAN                                65000000
NESTLE KITKAT Coklat Wafer 2F Original 17g x 6 pcs   2720000000
NESTLE KITKAT Coklat Wafer 2F Original 17g x 6pcs    2680000000
NanoNano Milky Permen Susu Cokelat 12 gr              240000000
Nestle Nestum Sereal Susu + Cokelat 1 x 128 gr       1340000000
Oreo Dutch Cocoa Wafer Choco Vanilla 140.4 gr         740000000
Pasha Dark Chocolate Compound Pack 250 gr            2240000000
Ritz Meses Cokelat 300 gr                            4400000000
Silver Queen Rockr 22 gr                              400000000
Silverqueen Very Berry 62 g                          2250000000
Silverqueen Very Berry 62 g x 2 pcs                  4000000000
Soyjoy Strawberry 30 gr Soyjoy Almond & Chocola...   1940000000
Tim Tam Choco Biskuit Chocolate 81 gr                 790000000
Toblerone Coklat Milk Box 100g Coklat Swiss Pre...   3360000000
Tulip Dark Compound Cokelat 250 gr                   2130000000
Twister Chocolate 80 g  x 4 pcs                      2670000000
WoCA Assorted Chocolate Bar WoCA 6x90 gram          11999900000
WoCA Coklat Kopi Luwak Chocolate Bar Premium Da...   1599900000
WoCA Coklat Original Premium Chocolate 90 gram       2199900000
WoCA Coklat Peppermint Premium Chocolate 90 gram     2199900000
WoCA Krunz Chocolate Dark 8 individual packs - ...   2499900000

In [105]:
pv.to_csv("shopee_product_price.csv")